### ISSUE TITLE
Atomic writes to database on activity destruction.

### ISSUE THREAD

**Issue by dzhou343** [dzhou343/YSC3232-LittleYNC#17]
When writing user info to the database after exiting an activity page (like cendana forest), we likely need to store the amount of resource gathered and then atomically do some kind of compare and swap with the DB when writing to ensure no conflict with something like a trade being completed.

**Comment by dzhou343** [comment]
@markyuen just tagging you here for visibility.

**Comment by markyuen** [comment]
Yep, noted!
